name: CDK diff workflow
on: 
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify aws cli
        run: |
          aws --version
          ls
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::392159187067:role/test-assume-role
          role-session-name: "githubsession"
      - name: Print s3 buckets
        run: |
          printenv
          aws s3 ls
      - name: Print github Context
        run: |
          echo "${{toJson(github)}}" > out.txt
          cat out.txt
      - name: Install Packages
        run: |
          npm init -y
          npm install aws-cdk-lib
          npm install aws-sdk
      #- name: cdk diff
       # run: cdk diff
