name: CDK diff workflow
on: 
  workflow_call: 

jobs:
  test-job-1:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify aws cli
        run: |
          aws --version
          ls
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-region: "ca-central-1"
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Print s3 buckets
        run: |
          aws s3 ls
      - name: Print github Context
        run: |
          echo "${{toJson(github)}}" > out.txt
          cat out.txt
      - name: Install Packages
        run: |
          npm init -y
          npm install aws-cdk-lib
          npm install aws-sdk
      #- name: cdk diff
       # run: cdk diff
