name: CDK diff workflow
on: 
  workflow_call: 

jobs:
  test-job-1:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
      - uses: actions/checkout@v4
      - run: |
          npm install aws-cdk-lib
          npm install aws-sdk