name: CDK diff workflow
on: 
  workflow_call: 

jobs:
  test-job-1:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify aws cli
        run: |
          aws --version
          ls
      - name: Print github Context
        run: |
          ${{toJson(github)}} > out.txt
          cat out.txt
      - name: Install Packages
        run: |
          npm init -y
          npm install aws-cdk-lib
          npm install aws-sdk
      #- name: cdk diff
       # run: cdk diff
