name: CDK diff workflow
on: 
  workflow_call: 

jobs:
  test-job-1:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: |
          pwd
          ls
          npm install -global aws-cdk-lib
          npm install -global aws-sdk
      - name: cdk diff
        run: which cdk
