name: CDK diff workflow
on: 
  workflow_call: 

jobs:
  test-job-1:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: |
          pwd
          ls
          npm init -y
          npm install aws-cdk-lib
          npm install aws-sdk
          ls
      - name: cdk diff
        run: npx cdk diff
