name: Hello World Workflow
run-name: Hello world is running!!!!
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: bye bye
        run: echo "Goodbye"
        shell: bash
