name: learn-github-actions
run-name: sample run from github
on:
  issue_comment:
    types: [created]
jobs:
  check-bats-version:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo " ${{ toJson(github.event)}}"
