name: learn-github-actions
run-name: sample run from github
on:
  issue_comment:
    types: created
jobs:
  check-bats-version:
    if: ${{github.event.issue.pull_request}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
      - run: echo "hello world"
