name: Print-Github-Context
run-name: print-github-context
on:
  issue_comment:
    types: [created]
jobs:
  print-gh-context:
    if: ${{ github.event.issue.body }}
    runs-on: ubuntu-latest
    steps:
      - run: echo " ${{ toJson(github.event)}}"
