name: Print-Github-Context
run-name: print-github-context
on:
  issue_comment:
    types: [created]
jobs:
  print-gh-context:
    permissions:
      pull-requests: write
    if: ${{ github.event.comment.body == 'run'}}
    runs-on: ubuntu-latest
    steps:
      - name: Save output
        run: echo "${{toJson(github.event.comment)}}" > out.txt
      - name: Print Output
        run: cat out.txt
      - name: print to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.issue.number}}
          body-path: "out.txt"
  calling-cdk-diff:
    permissions: write-all
    uses: ./.github/workflows/cdk-diff.yaml

  calling-cdk-deploy:
    permissions: write-all
    uses: ./.github/workflows/cdk-deploy.yaml
    needs: calling-cdk-diff 
