name: Print-Github-Context
run-name: print-github-context
on:
  issue_comment:
    types: [created]
jobs:
  print-gh-context:
    if: ${{ github.event.comment.body == 'run'}}
    runs-on: ubuntu-latest
    steps:
      - name: Save output
        run: echo ${{github.event.comment}} > out.txt
      - name: Print Output
        run: cat out.txt
      - name: print to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.issue.number}}
          body-path: ./out.text
